# Generated by Django 4.0.2 on 2022-03-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ser_image', models.ImageField(upload_to='', verbose_name='photos/%Y/%m/%d/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
